00:00.500-00:03.900 Nem is tudtam, hogy haditechnikai szakértővel van dolgom.
00:04.000-00:05.000 Ön tervezte az Avengert?
00:05.100-00:06.600 Nem, nem dehogy.
00:06.700-00:10.700 Egy fejlesztésnél körülbelül 1000-1200 ember dolgozik együtt.
00:10.800-00:15.000 Én egyike voltam azoknak, akik a hajtómű hűtőrendszerét alkották meg.
00:15.000-00:17.500 Minden csapat egy kutatólaboratóriumban van.
00:17.800-00:19.600 Különböző központok léteznek:
00:19.700-00:24.300 van hadászati, mechanikai, statikai és mesterséges intelligencia labor is.
00:24.400-00:26.000 Én a mechanikai részlegnél voltam.