00:00.000-00:01.800 Nem, az alvással semmi gondom.
00:01.900-00:03.000 A szakmai tanácsát kérném. 
00:03.100-00:05.800 Úgy tudom Ön foglalkozott régebben robotikával, igaz ez?
00:05.800-00:07.600 Robotok, Föld, igen.
00:07.800-00:13.300 Nagyon régen, a Földön, dolgoztam egy kutatólaboratóriumban, mint asszisztens. 
00:13.400-00:16.200 De a labor már nem régi, alig van munkájuk. 
00:16.300-00:20.200 Állítólag fegyvereket is terveztek a B4-es részlegben, 
00:20.300-00:22.200 de oda csak VIP kártyával lehet bejutni.