00:00.500-00:02.000 Mit ért ezalatt?
00:04.500-00:07.000 Nézze például a Garthogokat.
00:07.000-00:12.000 Az űrhajóik olyan gyorsak, hogy egyetlen földi cirkáló sem képes befogni őket.
00:12.400-00:15.500 Olyan gyorsan változtatnak irányt, hogy ez mindenkit meglep, 
00:15.510-00:19.000 még engem is, pedig én igazán sok csatában vettem részt.
00:19.500-00:21.500 Az az igazság, hogy nem nagyon kedvelem, 
00:21.510-00:24.500 ha az ellenfeleink ekkora technikai fölényben vannak.
