00:00.000-00:02.500 Seems your ability is only exceeded by your modesty.
00:02.600-00:04.000 Did you also design the Avenger?
00:04.500-00:08.000 Oh, no. I can't take credit for that project, I'm afraid.
00:08.500-00:10.000 It takes thousands of people. 
00:10.500-00:13.500 I worked on the cooling system for the quad engines.
00:13.600-00:17.000 Separate teams are responsible for each part of the project.
00:17.500-00:19.800 Happened to be, I was on the mechanics team.
00:20.000-00:21.500 There were other teams too, like:
00:21.600-00:25.000 civil engineering and artificial intelligence for example.