00:00.100-00:01.200 Okay, listen up Kelly!
00:01.700-00:03.200 We went through the academy together,
00:03.300-00:05.500 so I, I think I can trust you, can I?
00:06.000-00:09.100 I think there might be an alien spy on my ship.
00:09.300-00:11.600 Have you seen any strangers on board or anything?
00:11.700-00:13.600 Haha, aliens, don't make me laugh!
00:13.000-00:16.300 This ship isn't big enough to hide a rat,
00:16.400-00:18.100 let alone, an alien spy.
00:18.200-00:20.300 You gotta be crazy just to ask.
00:20.900-00:24.000 You know, paranoia is a side effect of ??? and brandy.