00:02.500-00:03.800 Sí, capitán, ¿qué pasa?
00:03.900-00:04.500 ¡Comandante! 
00:05.300-00:08.000 ¡Un planeta ha sido infectado por un virus!
00:08.100-00:09.400 ¿Pueden nuestros enemigos estar probando nuevos
00:09.500-00:11.400 armas biológicas en nuestra zona?
00:12.000-00:14.500 Nuestro reconocimiento nos lleva a pensar que sí.
00:14.600-00:17.400 Se han notificado casos similares en otros sectores.
00:17.600-00:21.100 Sin embargo, también se vieron allí unidades de transporte.
00:21.400-00:23.400 Recientemente hemos desarrollado nuevos sensores 
00:23.500-00:25.500 que pueden detectar portadores del virus.
00:26.400-00:28.300 Les enviaré algunos.
00:30.300-00:33.500 Su tarea sigue siendo eliminar las unidades portadoras del virus.
00:33.900-00:35.600 Mantenedme informado de vuestros progresos.