00:01.900-00:03.500 Lieutenant! ¡Lo ha hecho muy bien!
00:03.900-00:05.300 ¡Acaba de ser ascendido!
00:05.500-00:07.200 ¡Enhorabuena, comandante!
00:07.900-00:10.400 Abordará su nueva nave en el sector B-2.
00:10.900-00:14.100 El sector, donde estarás destinado, está cerca del Imperio Garthog.
00:14.900-00:17.800 Aparentemente, tu trabajo no se ha vuelto más fácil.
00:18.000-00:19.500 ¡Pero sé que te las arreglarás!
00:20.000-00:21.700 ¡Ten cuidado! ¡Buena suerte!