00:02.000-00.03.400 ¡Ah, teniente!
00:04.000-00:06.300 Este es el gobernador del planeta Naxos.
00:06.500-00:08.100 Nuestros sensores han detectado enormes
00:08.200-00:10.000 lecturas de energía no muy lejos de aquí.
00:10.100-00:11.900 Creemos que es una gran batalla.
00:12.500-00:15.100 Las naves en la zona no responden a nuestros mensajes.
00:15.200-00:17.300 ¡Te necesitamos para investigar! ¡Ahora!