00:00:800-00:03.500 Se ha reportado un virus desconocido en el planeta.
00:03.600-00:04.900 No hemos podido aislarlo
00:05.000-00:06.800 y creemos que es un virus transmisible por el aire.
00:07.000-00:09.700 ¡Ordeno cerrar este planeta a todo tráfico!
00:09.800-00:13.400 ¡Y no debes dejar que nadie escape o desembarque!
00:14.000-00:16.000 Necesitas poner en cuarentena el planeta
00:16.500-00:19.500 hasta que encontremos cómo derrotar el virus.