00:01.500-00:03.500 Creí que habías venido a poner en cuarentena el planeta,
00:03.600-00:05.000 ¡no a dirigir el tráfico!
00:05.300-00:08.700 ¡Reportaré este incidente incompetente a tu superior!
00:08.900-00:12.000 Este virus casi nos arruina de verdad.
00:13.000-00:17.200 ¡Pero logramos contenerlo a pesar de la falta de cooperación de tu parte!
00:18.300-00:21.000 Hay demasiadas muertes innecesarias, me temo.
00:21.500-00:23.600 ¡No puedo gobernar un planeta vacío!