00:00.900-00:02.800 Már megint egy új vírus kapitány.
00:03.000-00:04.900 A dolga ugyanaz, mint a múltkor.
00:05.200-00:08.300 Mindenesetre, furcsa ez a fertőzés.
00:08.500-00:13.200 A múltkori óta mindenkit megvizsgáltunk, aki csak a bolygóra tette a lábát,
00:13.300-00:17.300 de nem találtunk semmit; mintha a semmiből jönne elő...
00:17.800-00:21.700 Remélem ezt a járványt is hamar meg tudjuk fékezni.