00:00.100-00:03.500 Oh, so I take that you're not too keen on fighting.
00:03.600-00:06.000 Yeah, of course not. Especially since there is 
00:06.100-00:08.500 nothing like human about our enemies.
00:09.000-00:12.000 The biggest problem is you can't predict their reactions,
00:12.100-00:14.100 and you never know what they're thinking.
00:14.500-00:16.000 But I tell you what I'm thinking:
00:16.300-00:18.700 We've been to war with them for over thirty years,
00:19.000-00:20.600 and we still don't know anything about them.