00:00.100-00:02.900 I just wanted to see if you had a chance yet to
00:03.000-00:06.000 compile the results of the test I completed for you?
00:06.100-00:09.300 It's my job to examine all the crew on a spaceflights.
00:09.400-00:12.900 Some people get claustrophobic when confined in a small space.
00:13.000-00:16.000 They can react in a number of ways. Some go crazy,
00:16.100-00:18.000 while others get depressed, but either way,
00:18.100-00:22.000 I try to watch for tail-tale signs, and nothing really happens.
