00:00.000-00:03.700 Szeretném, ha mesélne arról a tesztről, amit ki kellett töltenem.
00:03.800-00:05.500 Megvan már az értékelése?
00:05.700-00:08.500 Mindenkivel kitöltetünk egy ilyen tesztet időnként.
00:09.000-00:12.000 Tudja, vannak emberek, akik nem bírják a bezártságot.
00:12.100-00:16.500 Mindenkinek szüksége van a tágas térre, az óceán látványára.
00:16.700-00:18.900 Vannak, akik nem bírják ezt sokáig. 
00:19.000-00:21.500 Az ilyen embereket minél hamarabb ki kell szűrnünk.