00:00.100-00:01.800 I must talk to Reinhart. 
00:01.900-00:04.500 It looks like he might be the only one who has answers for me.
00:04.600-00:07.100 Please, give me the old code. I might be able to use it,
00:07.200-00:08.500 somehow. I don't know.
00:09.000-00:13.100 Okay. I'll give you the code, but don't tell anybody I gave it to you.
00:13.300-00:15.300 The old code was: 
00:16.500-00:18.300 Alpha Z.