00:01.500-00:05.200 A célja a bolygó lezárása volt, és nem a forgalomirányítás.
00:05.400-00:08.900 Azt hiszem, Ön nem veszi komolyan a feladatát, Kapitány.
00:09.300-00:12.200 Jelentenem kell az esetet a felettesének.
00:12.900-00:17.500 Szerencsére ismét sikerült megfékeznünk a fertőzést, de sokan meghaltak.
00:17.700-00:21.400 Ha továbbra is ilyen sűrűn jönnek létre új vírusok,
00:21.500-00:23.900 nem sokan maradunk a bolygón.