00:00.800-00:01.600 Szia Dave!
00:01.700-00:02.900 Remélem, jól vagy.
00:03.000-00:04.800 Tegnap egy kiállításon voltunk Johnnyval.
00:04.900-00:07.100 Johnny, meséld el a papának, mit láttunk.
00:07.500-00:10.900 Képzeld, apu: láttunk sok űrhajót meg rakétát.
00:11.200-00:15.400 És az űrhajókon fegyverek is voltak, és meg lehetett őket fogni.
00:15.500-00:18.800 Mondd apu, ti hogy fértek be egy ilyen kis hajóba?
00:19.200-00:21.700 Mondtam már neked Johnny, hogy azok csak modellek voltak.
00:21.900-00:24.600 Na jó, most elbúcsúzom, gondolom sok a munkád.
00:25.000-00:27.700 Remélem hamarosan találkozunk. Szia!