00:00.100-00.03.900 That doesn't make any sense. What're you talking about. C'mon talk to me!
00:04.800-00:07.000 Well, you know, their ships are so fast, 
00:07.100-00:09.000 none of our cruisers can touch them,
00:09.100-00:11.500 and their flight paths are almost incalculable.
00:12.500-00:14.800 When we do get a lock on them, they move so fast,
00:14.900-00:16.300 that it doesn't make any difference.
00:17.000-00:19.300 Everytime I see it, it still suprises me.
00:19.500-00:23.000 How can we defeat something that is so much more advanced technologically.
00:23.300-00:25.000 We know so little about them.