00:00.100-00:03.500 ¿Qué sabes sobre robótica exactamente?
00:04.000-00:07.000 Sé que estaban llevando a cabo investigaciones sobre robots hace mucho tiempo.
00:07.500-00:09.500 Hubo algún tipo de accidente con un prototipo,
00:09.600-00:12.000 que se volvió loco y mató a ocho técnicos.
00:12.200-00:15.100 Como si no tuviéramos suficientes problemas con la guerra contra los extraterrestres,
00:15.200-00:18.500 sin que el ejército cree robots que maten humanos.
00:18.600-00:22.000 La investigación terminó allí y no se hicieron más preguntas.
00:22.200-00:26.000 Se rumorea que algunos de los mismos técnicos todavía trabajan para el gobierno
00:26.100-00:29.000 en proyectos aún más secretos.