00:00.000-00:02.500 Parece que tu habilidad solo es superada por tu modestia.
00:02.600-00:04.000 ¿También diseñaste el Avenger?
00:05.000-00:09.000 Oh, no. No puedo atribuirme el mérito de ese proyecto, temo.
00:09.300-00:10.800 Requiere miles de personas.
00:11.300-00:14.000 Trabajé en el sistema de enfriamiento para los motores cuádruples.
00:14.100-00:17.500 Equipos separados son responsables de cada parte del proyecto.
00:18.000-00:20.300 Resulta que estaba en el equipo de mecánicos.
00:20.500-00:22.200 También había otros equipos, como:
00:22.500-00:25.800 ingeniería civil e inteligencia artificial, por ejemplo.