00:00.100-00:03.000 Solo cuando necesitamos dormir, por la noche. Jeje, sí.
00:03.100-00:05.500 De todos modos, ¿sabes algo sobre la vida artificial?
00:05.800-00:07.000 ¿Sabes, como los robots?
00:07.500-00:09.700 Hmm. ¿Robótica? Sí.
00:10.300-00:12.800 Cuando era estudiante, fui asistente
00:12.900-00:14.900 en los laboratorios de investigación terrestre.
00:15.000-00:18.200 Pero las cosas han cambiado mucho desde que estuve allí.
00:18.600-00:21.900 Escuché decir que se están desarrollando nuevas armas
00:22.000-00:23.600 en el centro C4.
00:24.000-00:27.000 Pero necesitarás una tarjeta VIP para obtener cualquier detalle.