00:00.100-00:01.800 Debo hablar con Reinhart.
00:01.900-00:04.500 Parece que él podría ser elúnico que tiene respuestas para mí.
00:04.600-00:07.100 Por favor, dame el código antiguo. Tal vez pueda usarlo,
00:07.200-00:08.500 de alguna manera. No lo sé.
00:09.000-00:13.100 De acuerdo. Te daré el código, pero no le digas a nadie que te lo di.
00:13.300-00:15.300 El código antiguo era:
00:16.500-00:18.300 Alpha Z.