00:00.100-00:02.200 No, el sueño no es mi problema.
00:02.500-00:04.000 Lo que realmente necesito es tu
00:04.100-00:06.200 consejo profesional sobre mecánica y robótica.
00:06.500-00:08.500 Hmm, robótica. Sí.
00:09.000-00:12.500 Cuando era estudiante, fui asistente en el laboratorio de investigación terrestre.
00:12.800-00:15.200 Pero las cosas han cambiado mucho desde que estuve allí.
00:15.600-00:20.500 Escuché decir que se está desarrollando un nuevo arma en el centro C4.
00:20:600-00:23.500 Pero necesitas una tarjeta VIP para obtener cualquier detalle.