00:00.100-00.03.900 Eso no tiene sentido. ¿De qué estás hablando? ¡Vamos, háblame!
00:04.800-00:07.000 Bueno, sabes, sus naves son tan rápidas,
00:07.100-00:09.000 ninguno de nuestros cruceros puede alcanzarlas,
00:09.100-00:11.500 y sus trayectorias de vuelo son casi incalculables.
00:12.500-00:14.800 Cuando logramos fijar el objetivo en ellos, se mueven tan rápido,
00:14.900-00:16.300 que no hace ninguna diferencia.
00:17.000-00:19.300 Cada vez que lo veo, todavía me sorprende.
00:19.500-00:23.000 ¿Cómo podemos derrotar algo que es tecnológicamente mucho más avanzado?
00:23.300-00:25.000 Sabemos tan poco sobre ellos.