00:00.100-00:02.300 Hace tiempo que no toco esa cosas desde la universidad.
00:02.500-00:05.400 Pero podría jurar que vi a alguien salir corriendo de mi habitación.
00:05.700-00:07.500 ¡Estoy seguro de que alguien está espiándome!
00:07.600-00:10.300 No, no puedo creer que haya un alienígena en la nave.
00:10.500-00:13.000 Si te preocupa el espionaje, mantente alejado del Pro-brandy
00:13.100-00:14.300 y activa tu Grabador de Habitación.
00:14.700-00:17.800 Sabes, puedes grabar los movimientos de la habitación en tu computadora.
00:18.800-00:21.500 Todo lo que tienes que hacer es ponerlo en la posición REC.
00:22.000-00:25.100 Luego, sal de la habitación y la computadora grabará automáticamente los movimientos de cualquier persona que ingrese a la habitación.
00:27.800-00:28.900 Bastante simple, ¿no?