00:00.100-00:03.500 Oh, entonces supongo que no estás muy interesado en luchar.
00:03.600-00:06.000 Sí, por supuesto que no. Especialmente porque no hay nada humano en nuestros enemigos.
00:06.100-00:08.500 El mayor problema es que no puedes predecir sus reacciones,
00:12.100-00:14.100 y nunca sabes lo que están pensando.
00:14.500-00:16.000 Pero te diré lo que estoy pensando:
00:16.300-00:18.700 Hemos estado en guerra con ellos durante más de treinta años,
00:19.000-00:20.600 y aún no sabemos nada sobre ellos.