00:00.100-00:01.200 Bueno, escucha Kelly.
00:01.700-00:03.200 Pasamos juntos por la academia,
00:03.300-00:05.500 así que, creo que puedo confiar en ti, ¿no?
00:06.000-00:09.100 Creo que podría haber un espía alienígena en mi nave.
00:09.300-00:11.600 ¿Has visto a algún extraño a bordo o algo así?
00:11.700-00:13.600 Jaja, alienígenas, ¡no me hagas reír!
00:13.000-00:16.300 Esta nave no es lo suficientemente grande como para ocultar una rata,
00:16.400-00:18.100 y mucho menos un espía alienígena.
00:18.200-00:20.300 Tienes que estar loco solo por preguntar.
00:20.900-00:24.000 Sabes, la paranoia es un efecto secundario de ??? y brandy.