00:00.100-00:02.000 No creo que me esté volviendo loco,
00:02.500-00:04.800 pero tengo algunos sueños extraños.
00:05.100-00:08.900 De hecho, hay una habitación que sigue apareciendo en todos mis sueños.
00:09.100-00:11.600 Creo que he visto esa habitación cuando estaba consciente también.
00:11.800-00:12.600 ¿Qué opinas de eso?
00:14.500-00:18.000 Según la ciencia moderna, los sueños provienen del subconsciente.
00:18.100-00:21.500 Pero la mayoría de las veces es difícil determinar qué los causa.
00:22.000-00:24.100 Aquí estamos, en el siglo XXIV,
00:24.200-00:26.900 y no puedo creer que todavía no podamos comprender
00:27.000-00:28.200 el verdadero significado de los sueños.