00:00.100-00:02.900 Solo quería ver si has tenido la oportunidad de
00:03.000-00:06.000 compilar los resultados de la prueba que completé para ti.
00:06.100-00:09.300 Es mi trabajo examinar a toda la tripulación en los vuelos espaciales.
00:09.400-00:12.900 Algunas personas sufren de claustrofobia cuando están confinadas en un espacio pequeño.
00:13.000-00:16.000 Pueden reaccionar de diferentes maneras. Algunos se vuelven locos,
00:16.100-00:18.000 mientras que otros se deprimen, pero de cualquier manera,
00:18.100-00:22.000 trato de estar atento a las señales reveladoras y realmente no sucede nada.