00:00.700-00:03.300 Engem a Földön folyó kutatások érdekelnek.
00:03.400-00:05.900 Úgy tudom robotokat is fejlesztettek.
00:06.000-00:11.200 Igen, de a fejlesztéseket az állam már nagyon régen leállíttatta.
00:11.300-00:15.000 A kutatás akkori vezetője Reinhardt professzor volt. 
00:15.100-00:17.400 Nagyon sok órát adott nekünk az egyetemen. 
00:17.700-00:20.100 Nagyon rendes embernek ismertem meg.
00:20.500-00:25.400 Ő maradt a robot project sikertelensége után a csapatban, de sokakat menesztettek. 
00:25.500-00:29.900 És ő már csak, ugye, a fegyverek kifejlesztésén dolgozik.