00:02.300-00:03.700 Mi a helyzet, Kapitány?
00:03.800-00:07.700 Parancsnok! Rövid időn belül két új vírus ütötte fel a fejét a bolygón.
00:07.900-00:11.100 Nem lehet, hogy az ellenségeink biológiai fegyverekkel kísérleteznek?
00:11.900-00:14.600 Hhaa, a felderítés is erre gyanakszik,
00:14.700-00:17.800 más szektorokban is hasonló esetek történtek.
00:18.000-00:20.900 De ott szállítóegységeket is észleltek.
00:21.700-00:26.800 Viszont sikerült kifejleszteni új radarokat, amelyek azonosítják őket.
00:26.900-00:28.600 Önnek is küldünk egypárat.
00:30.000-00:33.900 De a szállítóegység megsemmisítése az Ön feladata.
00:34.200-00:36.400 Tájékoztasson az akcióról!