00:00.500-00:04.000 Meséljen, hogyan zajlik egy ilyen kutatás?
00:04.500-00:08.000 A kolóniákon kiemelt szerepe van a kutatóközpontoknak.
00:08.200-00:15.500 Mindegyik a legjobb, legmodernebb műszerekkel van felszerelve. Képzelheti, hogy mennyibe kerül egy ilyen kutatóközpont felállítása.
00:15.900-00:21.500 A különböző központok is összeköttetésben vannak egymással az úgynevezett direct linkkel.
00:21.600-00:28.000 Amikor az Avengeren dolgoztunk, három mechanikai, három sztatikai és két hadászati központ működött együtt.
00:28.300-00:34.000 Egy ilyen gép megtervezése sokkal nagyobb feladat, mint ahogy azt sokan gondolnák. És rengeteg a buktató is.
00:34.000-00:38.800 Rendkívül összehangolt munkára van szükség, hogy a gép a felszállópályára kerülhessen.