00:00.500-00:05.000 Nem is tudtam, hogy haditechnikai szakértővel van dolgom. Ön tervezte az Avengert?
00:05.100-00:10.700 Nem, nem dehogy. Egy fejlesztésnél körülbelül 1000-1200 ember dolgozik együtt.
00:10.800-00:15.000 Én egyike voltam azoknak, akik a hajtómű hűtőrendszerét alkották meg.
00:15.000-00:17.500 Minden csapat egy kutatólaboratóriumban van.
00:17.800-00:24.300 Különböző központok léteznek: van hadászati, mechanikai, sztatikai és mesterséges intelligencia labor is.
00:24.400-00:26.000 Én a mechanikai részlegnél voltam.