00:00.000-00:03.000 Maga szerint foglalkoznak még robotkutatással?
00:03.500-00:09.500 Régen foglalkoztak, de úgy tudom meghibásodott egy, és ez több ember halálába került.
00:10.000-00:18.500 Képzelheti, hogy mennyire örültek a katonai vezetők, amikor a médiákban megjelent a hír, hogy már nemcsak az ellenségtől kell félnünk, hanem még a saját robotjaink is ránktámadnak.
00:18.800-00:26.200 Ezután, ha jól tudom, mindenféle kutatást leállítottak. Viszont úgy emléxem, a kutatásban résztvevőket nem vonták felelősségre.
00:26.300-00:28.200 Mindenki maradt a pozíciójában.