00:00.200-00:03.300 Ha szüksége van bármilyen utánpótlásra, tudja hol talál meg.
00:03.500-00:07.500 Most viszont a segítségét kérném. Úgy tudom, ért valamennyit a robotokhoz.
00:07.500-00:10.500 Robotok, Föld, igen.
00:10.800-00:15.500 Nagyon régen, a Földön dolgoztam egy kutatólaboratóriumban, mint asszisztens.
00:16.000-00:19.100 A labor már nem a régi, alig van munkájuk. 
00:19.200-00:27.100 Állítólag... állítólag fegyvereket is terveztek a B4-es részlegben, de oda csak VIP kártyával lehetett bejutni.