00:00.000-00:05.500 Nézze, láttam, hogy valaki kifutott a szobámból, ami fel volt túrva. Maga mire gondolna?
00:07.000-00:13.500 Fogalmam sincs, ki lehetett. Hihetetlen, hogy valaki közülünk kémkedne, nem tudom elhinni.
00:14.000-00:21.000 Viszont ha mégis igaza van kapitány, és az illető profi, akkor vissza fog menni, hogy megtalálja, amit keresett.
00:21.500-00:29.100 Én a maga helyében felvételre állítanám a terminálomat, és ha megtudom ki az, alaposan ellátnám a baját.