00:00.000-00:02.700 Van egy-két érdekes álmom, ami megfejtésre vár.
00:02.800-00:06.000 Állandóan egy szobát látok álmomban, ami egy orvosi szobára hasonlít,
00:06.010-00:08.700 pedig biztos vagyok benne, hogy még sosem jártam ott.
00:09.000-00:12.000 Néha éber állapotomban is látom ezeket a képeket.
00:12.100-00:13.500 Maga szerint mi lehet ez?
00:14.300-00:17.400 Az álmok utalhatnak egy régi, elfeledett emlékre, 
00:17.500-00:19.000 amely csak most tört a felszínre.
00:19.500-00:22.100 De lehet ez csupán egy egyszerű képzelgés is, 
00:22.200-00:25.000 vagy egy nagyon erős vágyódás a család, az otthon után.
00:25.500-00:28.500 Sajnos erre ilyen gyorsan nem tudok határozott választ adni.