00:00.000-00:03.000 Maga szerint foglalkoznak még robotkutatással?
00:03.500-00:06.700 Régen foglalkoztak, de úgy tudom egyszer meghibásodott egy,
00:06.800-00:09.500 és ez több ember halálába került.
00:10.000-00:12.800 Képzelheti, hogy mennyire örültek a katonai vezetők, 
00:12.900-00:16.400 amikor a médiákban megjelent a hír, hogy már nemcsak az ellenségtől kell félnünk, 
00:16.500-00:18.500 hanem még a saját robotjaink is ránktámadnak.
00:18.800-00:22.100 Ezután, ha jól tudom, mindenféle kutatást leállítottak. 
00:22.200-00:26.200 Viszont úgy emléxem, a kutatásban résztvevőket nem vonták felelősségre.
00:26.300-00:28.200 Mindenki maradt a pozíciójában.