00:00.700-00:05.900 Engem a Földön folyó kutatások érdekelnek. Úgy tudom robotokat is fejlesztettek.
00:06.000-00:11.200 Igen, de a fejlesztéseket az állam már nagyon régen leállíttatta.
00:11.300-00:15.000 A kutatás akkori vezetője Reinhard professzor volt. 
00:15.100-00:20.100 Nagyon sok órát adott nekünk az egyetemen. Nagyon rendes embernek ismertem meg.
00:20.500-00:25.400 Ő maradt a robot project sikertelensége után a csapatban, de sokakat menesztettek. 
00:25.500-00:29.900 És ő már csak, ugye, a fegyverek kifejlesztésén dolgozik.