00:00.000-00:02.500 Úgy látom, nem nagyon kedveli ezeket a helyzeteket.
00:03.000-00:06.000 Nem hát, főleg a csatákat nem kedvelem.
00:06.300-00:08.500 Nem tetszenek nekem az ellenfeleink.
00:08.500-00:12.000 Nincsen bennük semmi... semmi emberi.
00:12.000-00:14.300 Nem tudni igazán, mire képesek.
00:14.500-00:20.300 Hiába harcolunk velük már több, mint harminc éve, nem tudunk róluk többet, mint az első csaták idején.