00:00.000-00:02.700 Van egy-két érdekes álmom, ami megfejtésre vár.
00:02.800-00:08.700 Állandóan egy szobát látok álmomban, ami egy orvosi szobára hasonlít, pedig biztos vagyok benne, hogy még sosem jártam ott.
00:09.000-00:13.500 Néha éber állapotomban is látom ezeket a képeket. Maga szerint mi lehet ez?
00:14.300-00:19.000 Az álmok utalhatnak egy régi, elfeledett emlékre, mely csak most tört a felszínre.
00:19.500-00:25.000 De lehet ez csupán egy egyszerű képzelgés is, vagy egy nagyon erős vágyódás a család, az otthon után.
00:25.500-00:28.500 Sajnos erre ilyen gyorsan nem tudok határozott választ adni.