00:02.700-00:09.900 3226-ban a Galaktikus Birodalom már a galaxis több, mint felét tarja uralma alatt.
00:11.000-00:14.000 A terület egyre nagyobb mértékű növekedése miatt
00:14.300-00:17.500 a vezetőség képtelen összetartani a Birodalmat.
00:18.300-00:24.900 Az egykor egységes birodalom kisebb részekre szakad, melyek között harcok dúlnak.
00:26.100-00:31.500 Az emberiség közel áll az első intergalaktikus háború kirobbanásához.
00:38.000-00:41.800 Egyre több bolygórendszert ragad magával a pusztító háború.
00:42.800-00:46.800 A veszteségek egyre nagyobbak, a vezetés tehetetlen.
00:48.000-00:51.500 Végső elkeseredésében a szenátus úgy dönt, 
00:52.300-00:57.000 beveti eddig titkolt fegyverét.