00:00.000-00:02.600 Miért szakított a kutatómunkájával? 
00:02.700-00:06.000 Úgy látom az elbeszélése alapján, hogy szerette azt a munkát.
00:07.300-00:12.500 Tudja, a túl sok munka, a túlfeszített tempó, nem az én stílusom.
00:12.800-00:17.600 Örökös hajtás van, túl szorosak a határidők, idegeskedés, meg a többi. 
00:17.700-00:22.000 A katonai vezetők is mindig a kutatókat okolják a vesztett csatákért.
00:22.300-00:25.300 Egyébként a főnökömmel se jöttem ki valami jól.
00:25.400-00:26.500 Így inkább otthagytam.
00:26.700-00:28.500 Igaz, hogy most kevesebbet keresek, 
00:28.600-00:32.200 de az a sok idegeskedés, ami ott volt, az nem nekem való.