00:00.000-00:04.290 Nézze, láttam, hogy valaki kifutott a szobámból, ami fel volt túrva. 
00:04.300-00:05.500 Maga mire gondolna?
00:07.000-00:09.100 Fogalmam sincs, ki lehetett. 
00:09.700-00:13.400 Hihetetlen, hogy valaki közülünk kémkedne, nem tudom elhinni.
00:14.000-00:17.500 Viszont ha mégis igaza van kapitány, és az illető profi, 
00:17.800-00:21.000 akkor vissza fog menni, hogy megtalálja, amit keresett.
00:21.500-00:25.600 Én a maga helyében felvételre állítanám a terminálomat,
00:25.610-00:29.100 és ha megtudom ki az, alaposan ellátnám a baját.