00:00.100-00:02.200 No, sleeping is not my problem.
00:02.500-00:04.000 What I really need is your professional
00:04.100-00:06.200 advice on mechanics and robotics.
00:06.500-00:08.500 Hmm, robotics. Yes I do.
00:09.000-00:12.500 When I was a student I was an assistant at the Earth research laboratory.
00:12.800-00:15.200 But things have really changed since I was there.
00:15.600-00:20.500 I heard tell, that a new weapon is being developed in the center C4.
00:20:600-00:23.500 But you need a VIP card to get any details.