00:00.000-00:02.800 Kelly, egy bizalmas kérdést intéznék Önhöz.
00:00.300-00:06.500 Remélem, bízhatom magában, és nem jut másnak a tudomására.
00:06.500-00:09.500 Maga szerint nem juthatott fel a hajónkra idegen?
00:10.500-00:12.500 Áh, idegen a hajón?
00:12.500-00:17.000 Ne vicceljen kapitány! Itt még egy patkány sem tud elbújni.
00:17.000-00:20.300 Tökéletesen átvizsgálunk mindent, ami a hajóra kerül.
00:21.000-00:23.200 De miből von le ilyen következtetést?