00:00.100-00:02.000 I don't think I'm going crazy, 
00:02.500-00:04.800 but I do have a few strange dreams.
00:05.100-00:08.900 In fact, there is this room that keeps reappering in all my dreams.
00:09.100-00:11.600 I think I've seen this room when I was councious too.
00:11.800-00:12.600 What do you make of that?
00:14.100-00:17.500 Regarding to modern science, dreams come from the subconcious.
00:17.600-00:21.500 But most the time, its difficult to tell what causes them.
00:22.000-00:23.600 Here we are, the 24th century,
00:23.700-00:26.500 and I can't believe we still can't seem to get a grasp 
00:26.600-00:28.200 on a dream's the true meaning.