00:00.100-00:03.500 What do you know about robotics?
00:04.000-00:07.000 I know they were conducting research on robots a long time ago.
00:07.500-00:09.500 There was some sort of accident with a prototype,
00:09.600-00:12.000 that went beserk and killed eight technicians.
00:12.200-00:15.100 As if we didn't have enough problems with the war against aliens,
00:15.200-00:18.500 without the military creating robots that killing humans.
00:18.600-00:22.000 The research ended there and no further questions were asked.
00:22.200-00:26.000 Rumor has it, that some of the same technicians are still working for the government
00:26.100-00:29.000 on even more secret projects.