00:02.500-00:03.800 Yes Captain, what is it?
00:03.900-00:04.500 Commander! 
00:05.300-00:08.000 A planet has been infected by a virus!
00:08.100-00:09.400 Can our enemies be testing new
00:09.500-00:11.400 biological weapons in our area?
00:12.000-00:14.500 Our reconissance leads us think so.
00:14.600-00:17.400 Similar cases were reported from other sectors.
00:17.600-00:21.100 However, transport units were also seen there.
00:21.400-00:23.400 We recently developed new sensors 
00:23.500-00:25.500 that can detect virus carriers.
00:26.400-00:28.300 I will dispatch some to you.
00:30.300-00:33.500 Your task is still to eliminate the virus carrier units.
00:33.900-00:35.600 Keep me informed of your progress!