00:00:800-00:03.500 An unknown virus has been reported on the planet.
00:03.600-00:04.900 We haven't been able to isolate it 
00:05.000-00:06.800 and we think its an airborne virus.
00:07.000-00:09.700 I order this planet closed from all traffic!
00:09.800-00:13.400 And you mustn't let anyoune escape or land!
00:14.000-00:16.000 You need to quarantine the planet
00:16.500-00:19.500 until we come up a way to defeat the virus.