00:01.900-00:03.500 Lieutenant! You've done well!
00:03.900-00:05.300 You've been just promoted!
00:05.500-00:07.200 Congratulations, Commander!
00:07.900-00:10.400 You'll be boarding your new ship in sector B-2.
00:10.900-00:14.100 The sector, where you'll be stationed, is near the Garthog Empire.
00:14.900-00:17.800 Apparently, your job hasn't gotten any easier.
00:18.000-00:19.500 But I know you will handle it!
00:20.000-00:21.700 Be careful! Good Luck!