00:50.500-00:53.500 Congratulations on your new appointment, Grant Admiral.
00:53.600-00:57.100 A new, very powerful race of aliens has been discovered.
00:57.300-01:01.900 This Dargslan race is proving to be a real threat to our security.
01:02.200-01:05.000 We don't think our empire will be able to prevail against
01:05.100-01:09.000 the new enemy without the cooperation of the other alien races.
01:09.100-01:12.500 We are creating a diplomacy annex on the Thorin.