00:00.100-00:02.000 I don't think I'm going crazy, 
00:02.500-00:04.800 but I do have a few strange dreams.
00:05.100-00:08.900 In fact, there is this room that keeps reappering in all my dreams.
00:09.100-00:11.600 I think I've seen this room when I was councious too.
00:11.800-00:12.600 What do you make of that?
00:14.500-00:18.000 According to modern science, dreams come from the subconcious.
00:18.100-00:21.500 But most the time, its difficult to tell what causes them.
00:22.000-00:24.100 Here we are, the 24th century,
00:24.200-00:26.900 and I can't believe we still can't seem to get a grasp 
00:27.000-00:28.200 on a dream's the true meaning.