00:00.000-00:02.500 Seems your ability is only exceeded by your modesty.
00:02.600-00:04.000 Did you also design the Avenger?
00:05.000-00:09.000 Oh, no. I can't take credit for that project, I'm afraid.
00:09.300-00:10.800 It takes thousands of people. 
00:11.300-00:14.000 I worked on the cooling system for the quad engines.
00:14.100-00:17.500 Separate teams are responsible for each part of the project.
00:18.000-00:20.300 Happened to be, I was on the mechanics team.
00:20.500-00:22.200 There were other teams too, like:
00:22.500-00:25.800 civil engineering and artificial intelligence for example.