00:01.500-00:03.500 I thought you were sent to quarantine the planet,
00:03.600-00:05.000 not to direct traffic!
00:05.300-00:08.700 I'll report this incompetent incident to your superior!
00:08.900-00:12.000 This virus almost ruined us for good.
00:13.000-00:17.200 But we managed to contain it despite the lack of cooperation from you!
00:18.300-00:21.000 There are too many unnecessary deaths I'm afraid.
00:21.500-00:23.600 I can't govern an empty planet.