00:00.500-00:01.800 Yes Captain, what is it?
00:01.900-00:02.500 Commander! 
00:03.300-00:06.000 A planet has been infected by a virus!
00:06.100-00:07.400 Can our enemies be testing new
00:07.500-00:09.400 biological weapons in our area?
00:10.000-00:12.500 Our reconissance leads us think so.
00:12.600-00:15.400 Similar cases were reported from other sectors.
00:15.600-00:19.100 However, transport units were also seen there.
00:19.400-00:21.400 We recently developed new sensors 
00:21.500-00:23.500 that can detect virus carriers.
00:24.400-00:26.300 I will dispatch some to you.
00:28.300-00:31.500 Your task is still to eliminate the virus carrier units.
00:31.900-00:33.600 Keep me informed of your progress!