00:50.500-00:53.500 Enhorabuena por su nuevo nombramiento, almirante Grant.
00:53.600-00:57.100 Se ha descubierto una nueva raza alienígena muy poderosa.
00:57.300-01:01.900 Esta raza Dargslan está demostrando ser una amenaza real para nuestra seguridad.
01:02.200-01:05.000 No creemos que nuestro imperio sea capaz de prevalecer contra
01:05.100-01:09.000 el nuevo enemigo sin la cooperación de las otras razas alienígenas.
01:09.100-01:12.500 Estamos creando un anexo diplomático en el Thorin.