00:00.100-00:03.000 Only when we need to sleep, at night. Heh, yeah.
00:03.100-00:05.500 Anyway, do you know anything about artificial life?
00:05.800-00:07.000 You know, like robots?
00:07.500-00:09.700 Hmm. Robotics? Yes I do.
00:10.300-00:12.800 When I was a student, I was an assistant
00:12.900-00:14.900 at the Earth research laboratories.
00:15.000-00:18.200 But things have really changed since I was there.
00:18.600-00:21.900 I heard tell, that some new weapons are being developed
00:22.000-00:23.600 in the center C4.
00:24.000-00:27.000 But you'll need a VIP card to get any details.