00:01.200-00:03.400 Parancsnok! A hajón kémkednek utánam!
00:03.500-00:06.000 Catherine, a pszichológusnő a szobámban kutatott.
00:06.800-00:11.100 A helyzet az, hogy időnként ellenőrizzük az embereinket, nehogy valami gond legyen.
00:11.300-00:14.700 A teszt, amit kapott, ezt a célt szolgálta.
00:15.000-00:19.000 Arra nem kapott utasítást a pszichológusnő, hogy kutasson.
00:19.300-00:21.900 Ezt majd én elintézem vele, legyen nyugodt.
00:22.100-00:24.000 További jó munkát, kapitány!